go/src/github.com/lgf133214/Gin/myblog/blog/urls.py
# -*-coding:utf-8-*-
"""myblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path, re_path
from blog.views import *
from django.views.static import serve


app_name = 'blog'

urlpatterns = [
    path('', index, name='index'),
    path('about.html', about, name='about'),
    path('contact.html', contact, name='contact'),
    path('search/', search, name='search'),
    path('blog/<int:bid>/', blog_detail, name='blog_detail'),
    path('login/', log_in, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('passwd/', PasswdView.as_view(), name='passwd'),
    path('reset/', reset, name='reset'),
    path('reset_email/', reset_email, name='reset_email'),
    path('setpd/', setpd, name='setpd'),
    path('validate/', Validate.as_view(), name='validate'),
    path('active/<str:active_code>', ActiveView.as_view(), name='active'),
    path('comment_sub/', comment_sub, name='comment_sub'),
    path('email_val/', email_val, name='email_val'),
    path('new_email_val/', new_email_val, name='new_email_val'),
    path('category/', category, name='category'),
    path('tag/', tag, name='tag'),
    path('all/', all, name='all'),
    path('send_contact_mail/', send_contact_mail, name='send_contact_mail'),
    path('subscript/', subscript, name='subscript'),
    path('subscript_val/', subscript_val, name='subscript_val'),
    path('username_val/', username_val, name='username_val'),
    path('change_info/', change_profile, name='change_info'),
    path('change_email/', change_email, name='change_email'),
    path('profile_modify/', profile_modify, name='profile_modify'),
    path('admin/upload/<str:dir_name>', upload_image, name='upload_image'),
    re_path(r'^upload/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, }),
]

go/src/github.com/lgf133214/Gin/myblog/myblog/urls.py
from django.urls import path, include
import blog.urls
from django.contrib import admin
from blog.views import page_not_found

urlpatterns = [
    path('feng_ge_66/', admin.site.urls),
    path('', include(blog.urls, namespace='myblog')),
]
handler404 = page_not_found

go/src/github.com/lgf133214/Gin/myblog/blog/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


# Create your models here.


# 访问网站的ip地址和次数
class Userip(models.Model):
    ip = models.CharField(verbose_name='IP地址', max_length=30)  # ip地址
    count = models.IntegerField(verbose_name='访问次数', default=0)  # 该ip访问次数
    last_visit = models.DateTimeField(verbose_name="上次访问时间", default=timezone.now)

    class Meta:
        verbose_name = '访问用户信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.ip


# 网站总访问次数
class VisitNumber(models.Model):
    count = models.IntegerField(verbose_name='网站访问总次数', default=0)  # 网站访问总次数

    class Meta:
        verbose_name = '网站访问总次数'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.count)


# 单日访问量统计
class DayNumber(models.Model):
    day = models.DateField(verbose_name='日期', default=timezone.now)
    count = models.IntegerField(verbose_name='网站访问次数', default=0)  # 网站访问总次数
    day_visit_ip = models.ManyToManyField(Userip, verbose_name="ip地址")

    class Meta:
        verbose_name = '网站日访问量统计'
        verbose_name_plural = verbose_name

    def __str__(self):
        return str(self.day)


class BlogUser(AbstractUser):
    nick_name = models.CharField('昵称', max_length=20, default='游客', blank=True)
    age = models.IntegerField('年龄', default=0)
    sex = models.CharField('性别', default='保密', max_length=3)
    cover = models.ImageField('头像', upload_to='images/user_icon/',
                              default='/static/images/user_icon_default.ico')
    views = models.IntegerField('热度', default=0)
    quote = models.CharField('格言', max_length=150, default='', blank=True)
    quote_author = models.CharField('格言出处', max_length=20, default='', blank=True)
    personal_profile = models.CharField('个人简介', max_length=500, default='', blank=True)

    class Meta:
        verbose_name = '用户'
        verbose_name_plural = verbose_name
        ordering = ['-id']

    def __str__(self):
        return self.username


class EmailSubscription(models.Model):
    email = models.EmailField(max_length=50, verbose_name="订阅者邮箱")
    sub_time = models.DateTimeField(verbose_name="订阅时间", default=timezone.now)
    user = models.ForeignKey(BlogUser, verbose_name='用户', on_delete=models.CASCADE, default=None)
    is_active = models.BooleanField("是否active", default=False)

    class Meta:
        verbose_name = '订阅者邮箱'
        verbose_name_plural = '订阅者邮箱'

    def __str__(self):
        return self.email


class EmailVerifyRecord(models.Model):
    code = models.CharField(verbose_name='验证码', max_length=50, default='')
    email = models.EmailField(max_length=50, verbose_name="邮箱")
    send_type = models.CharField(verbose_name="验证码类型",
                                 choices=(("register", "注册"), ("forget", "找回密码"), ("update_email", "修改邮箱")),
                                 max_length=30)
    send_time = models.DateTimeField(verbose_name="发送时间", default=timezone.now)

    class Meta:
        verbose_name = "邮箱验证码"
        # 复数
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)


class BlogCategory(models.Model):
    name = models.CharField('分类名称', max_length=20, default='')

    class Meta:
        verbose_name = '博客分类'
        verbose_name_plural = '博客分类'

    def __str__(self):
        return self.name


class Banner(models.Model):
    title = models.CharField('标题', max_length=50)
    cover = models.ImageField('轮播图', upload_to='images/banner',
                              default='/static/images/banner_default.png')
    link_url = models.CharField('图片链接', max_length=100)
    content = models.CharField('概述', max_length=200)
    is_active = models.BooleanField('是否active', default=False)
    category = models.ForeignKey(BlogCategory, verbose_name='分类', default=None, on_delete=models.DO_NOTHING, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '轮播图'
        verbose_name_plural = '轮播图'


class Tags(models.Model):
    name = models.CharField('标签名称', max_length=20, default='')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'

    def __str__(self):
        return self.name


class Post(models.Model):
    user = models.ForeignKey(BlogUser, verbose_name='用户', on_delete=models.CASCADE, default=None)
    category = models.ForeignKey(BlogCategory, verbose_name='博客分类', default=None, on_delete=models.DO_NOTHING)
    tags = models.ManyToManyField(Tags, verbose_name='标签')
    title = models.CharField('标题', max_length=50)
    content = models.TextField('内容')
    pub_date = models.DateTimeField('发布日期', default=timezone.now)
    update_date = models.DateTimeField('修改时间', default=timezone.now)
    cover = models.ImageField('博客封面', upload_to='images/post-cover', default='/static/images/post_cover_default.png')
    views = models.ManyToManyField(Userip, verbose_name='浏览数', blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '博客'
        verbose_name_plural = '博客'


class Comment(models.Model):
    post = models.ForeignKey(Post, verbose_name='博客', on_delete=models.CASCADE)
    user = models.ForeignKey(BlogUser, verbose_name='用户', on_delete=models.CASCADE, default=None)
    pub_date = models.DateTimeField('发布时间', default=timezone.now)
    content = models.TextField('内容')

    def __str__(self):
        return self.content

    class Meta:
        verbose_name = '评论'
        verbose_name_plural = '评论'


class Recommend(models.Model):
    title = models.CharField('标题', max_length=50)
    link = models.CharField('链接', max_length=50, default='')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '推荐'
        verbose_name_plural = '推荐'

go/src/github.com/lgf133214/Gin/myblog/templates/blog-details.html
{% extends 'base.html' %}
{% load cus_tags %}
{% block banner %}{% endblock %}
{% block main %}
    <!-- Page title -->
    <div class="page-title">
        <div class="container">
            <h2>{{ post.title }}</h2>
            <ul class="nav">
                <li><a href="{% url 'myblog:index' %}">Home</a></li>
                <li><a href="{% url 'myblog:category' %}?id={{ post.category.id }}">{{ post.category.name }}</a>
                </li>
                <li>作者：{{ post.user.nick_name }}</li>
            </ul>
        </div>
    </div>
    <!-- End of Page title -->

    <div class="container pt-120">
        <div class="row">
            <div class="col-lg-8 pb-80">
                <div class="post-details-cover">
                    <!-- Post Thumbnail -->
                    <div class="post-thumb-cover">
                        <div class="post-thumb" style="text-align: center">
                            <img src="{{ post.cover | cover_url }}" alt="" class="img-fluid" width="500px">
                        </div>
                        <!-- Post Meta Info -->
                        <div class="post-meta-info">
                            <!-- Category -->
                            <p class="cats">
                                <a href="{% url 'myblog:category' %}?id={{ post.category.id }}">{{ post.category.name }}</a>
                            </p>

                            <!-- Title -->
                            <div class="title">
                                <h2>{{ post.title }}</h2>
                            </div>

                            <!-- Meta -->
                            <ul class="nav meta align-items-center">
                                <li class="meta-author">
                                    <img src="{{ post.user.cover | cover_url }}" alt="" class="img-fluid">

                                    <a href="javascript:void(0);">{{ post.user.nick_name }}</a>
                                </li>
                                <li class="meta-date">发布日期：{{ post.pub_date|date:"Y-m-d" }}</li>
                                <li>最近修改：{{ post.update_date|date:"Y-m-d" }}</li>
                                <li class="meta-comments"><a href="#com"><i
                                        class="fa fa-comment"></i> {{ post.comment_set.count }}
                                </a>
                                </li>
                            </ul>
                        </div>
                        <!-- End of Post Meta Info -->
                    </div>
                    <!-- End oF Post Thumbnail -->

                    <!-- Post Content -->
                    <div class="post-content-cover my-drop-cap" >
                        <p>
                            {% autoescape on %}
                                {{ post.content | img_size:"100px" | add_class_img}}
                            {% endautoescape %}

                        </p>
                        <hr>
                        <p style="text-align:center;font-size:30px">The End</p>
                        <blockquote>
                            <p>
                                {{ post.user.quote }}
                            </p>
                            <cite>{{ post.user.quote_author }}</cite>
                        </blockquote>

                    </div>
                    <!-- End of Post Content -->

                    <!-- Tags -->
                    <div class="post-all-tags">
                        {% for tag in post.tags.all %}
                            <a href="{% url 'myblog:tag' %}?id={{ tag.id }}" style="z-index: 999;
    position: relative;">{{ tag.name }}</a>
                        {% endfor %}

                    </div>
                    <!-- End of Tags -->

                    <!-- Author Box -->
                    <div class="post-about-author-box">
                        <div class="author-avatar">
                            <img src="{{ post.user.cover | cover_url }}" alt="" class="img-fluid">

                        </div>
                        <div class="author-desc">
                            <h5><a href="javascript:void(0);"> {{ post.user.nick_name }} </a>
                            </h5>
                            <div class="description">
                                {{ post.user.personal_profile }}
                            </div>
                            <div class="social-icons">
                                email：{{ post.user.email }}
                            </div>
                        </div>
                    </div>
                    <!-- End of Author Box -->

                    <!-- Comments -->
                    <button class="btn btn-comment" type="button" data-toggle="collapse" data-target="#commentToggle"
                            aria-expanded="false" aria-controls="commentToggle" id="com">
                        Comments ({{ post.comment_set.count }})
                    </button>

                    <div class="collapse show" id="commentToggle">
                        <ul class="post-all-comments">
                            <li class="single-comment-wrapper">
                                <!-- Single Comment -->
                                {% for comment in post.comment_set.all %}
                                    <div class="single-post-comment">
                                        <!-- Author Image -->
                                        <div class="comment-author-image">
                                            <img src="{{ comment.user.cover | cover_url }}" alt="" class="img-fluid"
                                                 width="60px">
                                        </div>
                                        <!-- Comment Content -->
                                        <div class="comment-content">
                                            <div class="comment-author-name">
                                                <h6>{{ comment.user.nick_name }}</h6>
                                                <span> {{ comment.pub_date }} </span>
                                            </div>
                                            <p>{{ comment.content }}</p>
                                        </div>
                                    </div>
                                {% endfor %}
                                <!-- End of Single Comment -->

                            </li>

                        </ul>
                    </div>
                    <!-- End of Comments -->
                    <!-- Comment Form -->
                    <div class="post-comment-form-cover">
                        <h3>Write your comment</h3>
                        <p style="color: red" id="msg"></p>
                        <form class="comment-form" action="{% url "myblog:comment_sub" %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value="{{ post.id }}">
                            <div class="row">
                                {% if user.is_authenticated %}
                                    <div class="col-md-12">
                                <textarea class="form-control" id="comment" name="comment"
                                          placeholder="Write your comment"></textarea>
                                    </div>
                                    <div class="col-md-12">
                                        <button class="btn btn-primary" id="submit">Submit</button>
                                    </div>
                                {% else %}
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" id="email" name="email"
                                               placeholder="Email">
                                    </div>
                                    <div class="col-md-12">
                                <textarea class="form-control" id="comment" name="comment"
                                          placeholder="Write your comment (请先登录或填写已经注册并激活过的邮箱，否则无法完成评论)"></textarea>
                                    </div>
                                    <div class="col-md-12">
                                        <button class="btn btn-primary" id="submit">Submit</button>
                                    </div>
                                {% endif %}

                            </div>
                        </form>
                    </div>
                    <!-- End of Comment Form -->
                </div>
            </div>
            {% include 'slide.html' %}
        </div>
    </div>
    <div id="outerdiv" style="text-align: center;position: fixed;z-index: 1000;top: 0;left: 0;
    width: 100%;height: 100%;background-color: rgba(255,255,255,.9);">
        <img id="bigimg" style="height: auto;width: 46.6325%;border: 0;
        margin: auto;position: absolute;top: 0;bottom: 0;left: 0;right: 0;" src=""/>
    </div>
{% endblock %}
{% block cus_script %}
    <script>
        //图片放大
        $("#outerdiv").hide();
        $(function () {
            $(".img").mouseover(function () {
                $(this).css("cursor", "pointer");
            });

            $(".img").click(function () {
                var _this = $(this);//将当前的pimg元素作为_this传入函数
                imgShow("#outerdiv", "#bigimg", _this);
            });
        });

        function imgShow(outerdiv, bigimg, _this) {
            var src = _this.attr("src");//获取当前点击的pimg元素中的src属性
            $('#outerdiv').attr('display', 'block');
            $(bigimg).attr("src", src);//设置#bigimg元素的src属性
            $(outerdiv).fadeIn("fast");

            $(outerdiv).click(function () {//再次点击淡出消失弹出层
                $(this).fadeOut("fast");
            });
        }



        {% if not user.is_authenticated %}
            var reg = /^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/;
            $(function () {
                    var arrayObj = [0, 0];
                    $.ajaxSetup({
                        data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
                    });
                    $("#email").blur(function () {
                        var email = $("#email").val();
                        if (reg.test(email)) {
                            $("#msg").html("请稍等。。。");
                            $.ajax({
                                type: "POST",
                                url: "{% url 'myblog:email_val' %}",
                                data: {
                                    email: $("#email").val()
                                },
                                dataType: "JSON",
                                success: function (data) {
                                    arrayObj[0] = data['status'];
                                    $("#msg").html(data['msg']);
                                }, error: function () {
                                    $("#msg").html('出错了， 等会儿试试看吧');
                                }
                            })
                        } else {
                            $("#msg").html("邮箱格式错误");
                        }
                    })
                    ;
                    $("#comment").blur(function () {
                        var comment = $("#comment").val();
                        if (comment && $.trim(comment)) {
                            arrayObj[1] = 1;
                        } else {
                            $("#msg").html("评论不能为空！");
                        }
                    });
                    $('#submit').click(function () {
                        if (arrayObj[0] + arrayObj[1] == 2) {
                            $('form').submit();
                        } else {
                            $("#msg").html("咋不按套路来呢？");
                            return false
                        }
                    });
                }
            );
        {% else %}
            $('#submit').click(function () {
                var comment = $("#comment").val();
                if (comment && $.trim(comment)) {
                    $("form").submit();
                } else {
                    $("#msg").html("评论不能为空！");
                    return false
                }
            });
        {% endif %}
    </script>
{% endblock %}
{% block subscript %}{% endblock %}

go/src/github.com/lgf133214/Gin/myblog/templates/index.html
{% extends 'base.html' %}
{% block cus_head %}
    <meta name="keywords" content="Feng`s blog,李高峰的博客,个人网站,技术分享" />
    <meta name="description" id="description" content="李高峰|李高峰的博客|django搭建个人博客|如何建立自己的网站" />
    <meta name="author" content="李高峰" />
{% endblock %}




go/src/github.com/lgf133214/Gin/myblog/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="ch">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}登录{% endblock %}</title>
    <link rel="icon" href="{% static 'images/favicon.png' %}">
    <script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
    <script src="{% static 'js/img_ver.js' %}"></script>

    <style>
        {% block cus_style %}{% endblock %}
        .bxs-row {
            margin-bottom: 12px;
        }

        .logo-box {
            width: 404px;
            margin: 120px auto;
            border: 1px solid #e5e5e5;
            border-radius: 4px;
            box-shadow: 0 4px 18px rgba(0, 0, 0, 0.2);
            position: relative;
            overflow: hidden;
            height: 360px;
        }

        .login {
            position: absolute;
            width: 320px;
            left: 0;
            top: 0;
            padding: 42px 42px 36px;
            transition: all 0.8s;
        }

        .username, .password, .email, .btn {
            height: 44px;
            width: 100%;
            padding: 0 10px;
            border: 1px solid #9da3a6;
            background: #fff;
            text-overflow: ellipsis;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            -khtml-border-radius: 4px;
            border-radius: 4px;
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
            color: #000;
            font-size: 1em;
            font-family: Helvetica, Arial, sans-serif;
            font-weight: 400;
            direction: ltr;
            font-size: 13px;
        }

        .submit {
            background-color: #0070ba;
            color: #fff;
            border: 1px solid #0070ba;
        }

        .submit:hover {
            background-color: #005ea6;
        }

        .verBox {
            position: absolute;
            width: 100%;
            text-align: center;
            left: 404px;
            top: 0;
            opacity: 0;
            transition: all 0.8s;
            padding-top: 55px;
        }

        .err {
            margin: 12px 0 0;
            line-height: 12px;
            height: 12px;
            font-size: 12px;
            color: red;
        }

        .slider-btn {
            position: absolute;
            width: 44px;
            height: 44px;
            left: 0;
            top: -7px;
            z-index: 12;
            cursor: pointer;
            background-image: url({% static 'images/login/sprite.3.2.0.png' %});
            background-position: 0 -84px;
            transition: inherit
        }

        .ver-tips {
            position: absolute;
            left: 0;
            bottom: -22px;
            background: rgba(255, 255, 255, .9);
            height: 22px;
            line-height: 22px;
            font-size: 12px;
            width: 100%;
            margin: 0;
            text-align: left;
            padding: 0 8px;
            transition: all .4s
        }

        .slider-tips {
            bottom: 0
        }

        .ver-tips i {
            display: inline-block;
            width: 22px;
            height: 22px;
            vertical-align: top;
            background-image: url({% static 'images/login/sprite.3.2.0.png' %});
            background-position: -4px -1229px
        }

        .ver-tips span {
            display: inline-block;
            vertical-align: top;
            line-height: 22px;
            color: #455
        }

        .active-tips {
            display: block
        }

        .hidden {
            display: none
        }

        .re-btn {
            position: absolute;
            left: 0;
            bottom: 0;
            height: 28px;
            padding: 0 16px
        }

        .re-btn a {
            display: inline-block;
            width: 14px;
            height: 14px;
            margin: 7px 0;
            background-image: url({% static 'images/login/sprite.3.2.0.png' %});
            background-position: 0 -1179px;
            cursor: pointer
        }

        .re-btn a:hover {
            background-position: 0 -1193px
        }

        .submit:hover {
            cursor: pointer;
        }

        a {
            text-decoration: none;
            color: #08acee;
        }

        a:active, a:hover {
            outline: 0;
        }

        a {
            color: #333;
        }

        a:hover {
            color: #bbb;
        }
    </style>

</head>
<body>

<div class="logo-box">
    <div class="login" style="">
        <div class="bxs-row" style="text-align:center;">
            <img id="logo" src="{% static 'images/login/logo.jpg' %}" style="width:72px;"><span class="tips"
                                                                                                style="color:red;">{% if active_msg %}
            {{ active_msg }}{% else %}忍住不哭来段口技{% endif %}</span>
        </div>
        <div class="bxs-row">
            <input type="text" class="username" id="uname" placeholder="用户名(推荐)/邮箱"
                   value="{% if uname %}{{ uname }}{% else %}admin{% endif %}">
            <p class=" err err-username">{{ error_msg }}</p>
        </div>
        <div class="bxs-row">
            <input type="password" class="password" id="passwd" placeholder="密码">
            <p class="err err-password"></p>
        </div>
        {% block custom %}{% endblock %}
        <div class="bxs-row">
            <input type="submit" class="submit btn" value="{% block btn %}登录{% endblock %}">
        </div>
    </div>
    <div class="verBox">
        <div id="imgVer" style="display:inline-block;"></div>
    </div>
</div>
<script>
    imgVer({
        el: '$("#imgVer")',
        width: '260',
        height: '116',
        img: [
            "{% static 'images/login/ver-1.png' %}",
            "{% static 'images/login/ver-2.png' %}",
            "{% static 'images/login/ver-3.png' %}",
        ],
        success: function () {
            $(".login").css({
                "left": "0",
                "opacity": "1"
            });
            $(".verBox").css({
                "left": "404px",
                "opacity": "0"
            });
            $(".tips").html('请稍等。。。');
            {% block post %}
                $.ajaxSetup({
                    data: {csrfmiddlewaretoken: '{{ csrf_token }}'},
                });
                $.ajax({
                    type: "POST",
                    url: "{% url 'myblog:validate' %}",
                    data: {
                        username: $("#uname").val(),
                        password: $("#passwd").val()
                    },
                    dataType: "JSON",
                    success: function (data) {
                        $(".err-username").html(data['error_msg']);
                        if (data['id'] == '0') {
                            $(".tips").html(data['tip']);
                            $("#logo").attr("src", "{% static 'images/login/login-err.png' %}")
                        } else if (data['id'] == '1') {
                            $(".tips").html(data['tip']);
                            $("#logo").attr("src", "{% static 'images/login/login-err.png' %}")
                        } else if (data['id'] == '2') {
                            window.location = '{% url 'myblog:index' %}'
                        }
                    }, error: function () {
                        $(".tips").html('出错了，等会儿试试看吧');
                        $("#logo").attr("src", "{% static 'images/login/login-err.png' %}")
                    }
                });
            {% endblock %}
        },
        error: function () {
        }
    });

    var reg = /^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/;


    $(".submit").on('click', function () {
        if (!$(".username").val()) {
            {#$(".err-username").html('杂种！！你用户名呢！？？？');#}
            $(".tips").html('老兄！！你用户名呢！？？？');
            $("#logo").attr("src", "{% static 'images/login/null-password.jpg' %}")
        } else if (!$(".password").val()) {
            {#$(".err-password").html('畜生！！你密码呢！？？？');#}
            $(".tips").html('老兄！！你密码呢！？？？');
            $("#logo").attr("src", "{% static 'images/login/null-password.jpg' %}")
        } {% block fill %}{% endblock %} else {
            $(".login").css({
                "left": "-404px",
                "opacity": "0"
            });
            $(".verBox").css({
                "left": "0",
                "opacity": "1"
            })
        }
    });
    {% if uname %}
        $("#uname").val({{ uname }});
        $("#passwd").val({{ passwd }});
    {% endif %}
</script>
<div style="text-align:center;">
    {% block foot %}
        <a href="{% url 'myblog:passwd' %}">忘记密码？</a>
        <a href="{% url 'myblog:register' %}">还没有账号？->注册</a>
    {% endblock %}
    <a href="{% url 'myblog:index' %}">回首页</a>
</div>
</body>
</html>